server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: autenticacao-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/auth/**
        
        - id: pedidos-service
          uri: ${PEDIDOS_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/pedidos/**
        
        - id: rastreamento-service
          uri: ${RASTREAMENTO_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/localizacoes/**
        
        - id: notificacao-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/notification/**

jwt:
  secret: ${JWT_SECRET:mySecretKey1234567890123456789012345678901234567890}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha 