server:
  port: 8083

spring:
  application:
    name: rastreamento-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rastreamento_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:daviffsilva}
    password: ${DB_PASSWORD:1234}
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  security:
    user:
      name: admin
      password: admin

# Authentication service configuration
auth:
  service:
    url: http://localhost:8081

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey1234567890123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api/rastreamento/api-docs
  swagger-ui:
    path: /api/rastreamento/swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: com.entregas.rastreamento.controller

# Logging
logging:
  level:
    com.entregas: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.socket: DEBUG 